# Generated by Django 6.0.4 on 2026-05-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_genre_slug_remove_movie_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='catalog.movie'),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
